### PR TITLE
Updating hieradata hostnames/ips to work in default profile and worker manager profiles

### PR DESCRIPTION
**Pull request by lasinducharith**
Although this is an optional change to the data layer(hiera), this will be helpful in VM scenario to,
- Avoid UnknownHostException if default profile is used without altering hiera default.yaml
- Have multiple workers, local_member_host should be a variable.

### CODE REVIEW

**Comment by imesh** [comment]
@lasinducharith Can you please explain the reason for replacing hostname values with "%{::hostname}"?

**Comment by lasinducharith** [comment]
@imesh default.yaml should represent the default wso2 product profile. IMO if somebody requests the default profile, it would be better if we can configure it using wso2/puppet-modules OOTB without a user having to change hieradata. As mentioned above, if user does not update the wso2::hostname in current default.yaml, it will throw a UnknownHostException at the server startup, due to hostname mismatch with what is in the /etc/hosts vs carbon.xml. So above change will make sure you always have the instance hostname in the carbon.xml(of course user can change it later)

I know what ever changes to hieradata is optional, since it's the data layer for puppet, but for the sake of simplicity in VM scenario, the above change can be useful for the end user who is trying out wso2.puppet modules for the first time.

**Comment by chamilad** [comment]
This can be tackled by adding a host_mapping entry AFAIK. 

We've refactored wso2/puppet-modules to separate Kubernetes and VM (default) platform specific configuration data. May be @lasinducharith can refactor this, so the requirement becomes clear?

**Comment by chamilad** [comment]
Closing as proposed solution is obsolete.

**Pull request closed without merging**
